name: SoundShip
favicon: null
layout_spectrum: 0.6764275627210736
typography_spectrum: 0.9506532296072692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.46105872467160225
  lightness: 0.890475258929655
  saturation: 0.3444337479304522
  rhythmicContrast: 0.16259542386978865
purpose: []
