favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.2178172
  brandStrength: 0.4610587246716022
  lightness: 0.8484142
  brandColors:
    - '#FFFFFF'
    - '#010001'
    - '#8A8A8F'
    - '#E07F4B'
    - '#C6C5C7'
  rhythmicContrast: 0.8554105
typography_spectrum: 0.9506532296072692
layout_spectrum: 0.463153
analytics:
  twitter: null
  google: null
  facebook: null
name: SoundShip
